//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled 260CT
//  @ File Name : managerAgent.java Customer List
//  @ Date : 17/03/2016 17/03/2015
//  @ Author :  Toby Marshall
//
//

import java.util.ArrayList;


public class managerAgent {
    
    private customerList list = new customerList();
        
    public managerAgent(){
    }        


	public void RegisterNewMember(String name, String paymentinfo,String contactDet, String address,String ID,String Pass ) {
	list.addNewMember(name,paymentinfo,contactDet,address,ID,Pass);
	}
	
        public void RegisterNewNoNMember(String name, String paymentinfo ) {
	list.addNewNonMember(name,paymentinfo);
	}	
	public void DeleteMember(int Ref) {
	list.deleteMem(Ref);
	}
        
        public void DeleteNonMember(int Ref){
        list.deleteNonMem(Ref);
        }
	
	public void viewCustomer( int Ref) {
	list.viewCustomer(Ref);
	}
        public void viewAllMembers(){
        list.viewMembers();
            
        }
        public void viewAllNonMembers(){
        list.viewNonMembers();
        }
        public int returnIsMem(int ref){
            if (list.findMember(ref) == 1){
                return list.findMember(ref);
            }
            else{
                return list.findnonMember(ref);
            }
        }

}
