//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled 260CT
//  @ File Name : MemberRepo.java Customer List
//  @ Date : 17/03/2016 17/03/2015
//  @ Author :  Toby Marshall
//
//



import java.util.ArrayList;


public interface MemberRepo {

    public ArrayList<Member> getAllMembers();
    public void addMember(Member memb);
    public void updateMember(Member memb);
    public void deleteMember(Member memb);
}

