//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled 260CT
//  @ File Name : nonMemberRepo.java Customer List
//  @ Date : 17/03/2016 17/03/2015
//  @ Author :  Toby Marshall
//
//

import java.util.ArrayList;


public interface nonMemberRepo {

    public ArrayList<nonMember> getAllNonMembers();
    public void addNonMember(nonMember non);
    public void updateNonMember(nonMember non);
    public void deleteNonMember(nonMember non);
}
