//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled 260CT
//  @ File Name : nonMember.java Customer List
//  @ Date : 17/03/2016 17/03/2015
//  @ Author :  Toby Marshall
//
//




public class nonMember {
	private int Ref = -1;
	private String paymentInformation = "";
	private String Name = "";
        private int isMember = 2;

	public String getName() {
            return Name;
	}
	
	public void setName(String aName) {
	Name = aName;
	}
	
	public String getPaymentInformation() {
	return paymentInformation;
	}
	
	public void setPaymentInformation(String aPayment) {
	paymentInformation = aPayment;
	}
	
	public int getRef() {
	return Ref;
	}
	
	public void setRef(Integer aRef) {
	Ref = aRef;
	}
        public void setisMember(){
            isMember = 1;
        }
        public int getIsMember(){
            return isMember;
        }
        
}
