//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled 260CT
//  @ File Name : nonmemberRepoImpl.java Customer List
//  @ Date : 17/03/2016 17/03/2015
//  @ Author :  Toby Marshall
//
//



import java.util.ArrayList;

public class nonmemberRepoImpl implements nonMemberRepo {    
    private ArrayList<nonMember> nonMembers;
     
    
    public void nonRepository(){
        nonMembers = new ArrayList<nonMember>();
    }        

    public void addNonMember(nonMember non){ //same as member, adds to array list
        nonMembers.add(non); 
    } 

    public nonMember getNonMembers(int ref){
        return nonMembers.get(ref); 
    }
    
    public ArrayList<nonMember> getAllNonMembers(){
        return nonMembers; 
    } 

    public void updateNonMember(nonMember non){ //not implimented yet, would allows the chanign of arrayList nonMembers attributes
            nonMembers.get(non.getRef()).setName(non.getName());
            System.out.println("Member Ref: "+ non.getRef()+ "updated");
    }
    
    public void deleteNonMember(nonMember non){ 
            nonMembers.remove(non.getRef());
            System.out.println("Member Ref: "+ non.getRef()+ "deleted");
    }

}